### ISSUE TITLE
Build exe

### ISSUE THREAD

**Issue by noahkiss** [Skippeh/SteamAccountSwitcher#1]
Hey Skippy, trying to figure out how to build a standalone exe. I opened the project in VS and deleted the lsproj folder, and I'm able to build and find the exe in the bin > release folder, but it'll only launch inside that folder and not standalone. How can I include the dependencies in the standalone exe? 

If it's easier for you, could you just send me the completed exe of your branch? It looks a lot cleaner from what I've seen. Thanks!

**Comment by Skippeh** [comment]
Not sure if you can "embed" the dependant dll files in the exe. Why can't you copy the exe along with all the dll files?

**Comment by noahkiss** [comment]
Hm, when I do that and run it it doesn't seem to be saving anything to the accounts.ini file the way the W3D3's does. Not sure how exactly to "install" it like the original one

**Comment by Skippeh** [comment]
Weird. Does the program have write permission to the directory accounts.ini is?

**Comment by Skippeh** [comment]
Turns out the file wasn't being saved at any point. Not sure how that happened. :)
